### ISSUE TITLE
python error when installing share-kit-vue on windows

### ISSUE THREAD

**Issue by mcorning** [hellobloom/share-kit-vue#5]
after unloading [(https://github.com/hellobloom/share-kit)] into VS Code, `npm i `returned this error four times on **Windows**:

```
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: C:\Users\mcorn\AppData\Local\Programs\Python\Python38-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
```

reported four times:

1. npm ERR! Failed at the keccak@1.4.0 rebuild script.
2. npm ERR! Failed at the secp256k1@3.7.1 intall and rebuild scripts
3. npm ERR! Failed at the sha3@1.2.3 install script.

**Comment by JaceHensley** [comment]
Can you try to reproduce on a fresh/empty npm project?

```
npm init
npm install @bloomprotocol/share-kit-vue // this will install share-kit as well
```

It may be related to some of the libraries we use in one of the dependencies

**Comment by mcorning** [comment]
Same failed result.



Rwap
^m

**Comment by edhedges** [comment]
@mcorning Hello Michael,

This seems to be a known problem that occurs for projects that use `node-gyp` as a dependency. I was able to reproduce your issue on a fresh `npm` project and the error output to my terminal led me to this section of documentation: https://github.com/nodejs/node-gyp#installation.

I ended up installing Python 3.8, adding it to my path, and then the installation command from the README worked!

```
npm install --save @bloomprotocol/share-kit-vue
```

Would you mind trying that and seeing if it resolves the issue? If so, we will update our README to help future users from running into the same problem. If installing Python doesn't resolve your issue, it may require you follow the installation instructions for `node-gyp` more closely, but either way we look forward to hearing back from you.

**Comment by mcorning** [comment]
Actually, I think there’s another source of confusion: unzipping the file in the Bloom folder gives me two (sub)folders. When I do your commands from the lowest folder I get this error instead:

npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "@bloomprotocol/share-kit-vue" under a package
npm ERR! also called "@bloomprotocol/share-kit-vue". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!


If I do the npm I in the first subfolder of bloom parent, I get the error I’ve been reporting below.

I’m totally confused now. Sorry for being such a blockhead.



Rwap
^m


From: Michael Corning
Sent: Monday, April 27, 2020 8:11 PM
To: hellobloom/share-kit-vue <reply@reply.github.com>; hellobloom/share-kit-vue <share-kit-vue@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [hellobloom/share-kit-vue] python error when installing share-kit-vue on windows (#5)

Same failed result.



Rwap
^m

**Comment by edhedges** [comment]
@mcorning I'm not sure what you're attempting, but I did the following on a windows machine:

1. Create a brand new folder for my project.
2. Navigate to it and run `npm init` to setup a new node project.
3. Try to install `@bloomprotocol/share-kit-vue` and watch it fail. From this error, I was pointed to the `node-gyp` documentation and the need for Python.
4. Install Python 3.8, add it to my path.
5. Try again to install via `npm install --save @bloomprotocol/share-kit-vue` and it worked.

I may be able to assist you better if you start with a fresh folder / project and provide me with more information on what you're attempting to accomplish.

**Comment by mcorning** [comment]
Switched my email address.

I already have python3.8 in VS Code. How will we confirm the path is set correctly?



Rwap
^m

**Comment by edhedges** [comment]
@mcorning The simplest way to verify that it's in your path is to open the command prompt/terminal of your choice and type `python`. When I installed python it was at
`C:\Users\Eddie\AppData\Local\Programs\Python\Python38` and I added it via
<img width="410" alt="image" src="https://user-images.githubusercontent.com/825537/80541011-3f974c80-895f-11ea-9e97-cc14a3b3078c.png">

<img width="598" alt="image" src="https://user-images.githubusercontent.com/825537/80541036-4b830e80-895f-11ea-9fbd-a2795cb09a01.png">
